// Generated by gencpp from file offboard/ThreePointMsg.msg
// DO NOT EDIT!


#ifndef OFFBOARD_MESSAGE_THREEPOINTMSG_H
#define OFFBOARD_MESSAGE_THREEPOINTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace offboard
{
template <class ContainerAllocator>
struct ThreePointMsg_
{
  typedef ThreePointMsg_<ContainerAllocator> Type;

  ThreePointMsg_()
    : header()
    , prev()
    , ctrl()
    , next()
    , duration(0.0)
    , max_acc(0.0)
    , acc_per_err(0.0)  {
    }
  ThreePointMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , prev(_alloc)
    , ctrl(_alloc)
    , next(_alloc)
    , duration(0.0)
    , max_acc(0.0)
    , acc_per_err(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _prev_type;
  _prev_type prev;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _ctrl_type;
  _ctrl_type ctrl;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _next_type;
  _next_type next;

   typedef double _duration_type;
  _duration_type duration;

   typedef double _max_acc_type;
  _max_acc_type max_acc;

   typedef double _acc_per_err_type;
  _acc_per_err_type acc_per_err;




  typedef boost::shared_ptr< ::offboard::ThreePointMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard::ThreePointMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ThreePointMsg_

typedef ::offboard::ThreePointMsg_<std::allocator<void> > ThreePointMsg;

typedef boost::shared_ptr< ::offboard::ThreePointMsg > ThreePointMsgPtr;
typedef boost::shared_ptr< ::offboard::ThreePointMsg const> ThreePointMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard::ThreePointMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard::ThreePointMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace offboard

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'offboard': ['/home/yoni/catkin_ws/src/offboard/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::offboard::ThreePointMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard::ThreePointMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard::ThreePointMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard::ThreePointMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard::ThreePointMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard::ThreePointMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard::ThreePointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "650650bb6026facc7a996bdd041b7323";
  }

  static const char* value(const ::offboard::ThreePointMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x650650bb6026faccULL;
  static const uint64_t static_value2 = 0x7a996bdd041b7323ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard::ThreePointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard/ThreePointMsg";
  }

  static const char* value(const ::offboard::ThreePointMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard::ThreePointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point prev\n\
geometry_msgs/Point ctrl\n\
geometry_msgs/Point next\n\
float64 duration\n\
float64 max_acc\n\
float64 acc_per_err\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::offboard::ThreePointMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard::ThreePointMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.prev);
      stream.next(m.ctrl);
      stream.next(m.next);
      stream.next(m.duration);
      stream.next(m.max_acc);
      stream.next(m.acc_per_err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThreePointMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard::ThreePointMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard::ThreePointMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "prev: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.prev);
    s << indent << "ctrl: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.ctrl);
    s << indent << "next: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.next);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
    s << indent << "max_acc: ";
    Printer<double>::stream(s, indent + "  ", v.max_acc);
    s << indent << "acc_per_err: ";
    Printer<double>::stream(s, indent + "  ", v.acc_per_err);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_MESSAGE_THREEPOINTMSG_H
